spring:
  application:
    name: conveyor

server:
  port: ${SERVER_PORT:8080}

app:
  credit:
    rate: 16

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
