apiVersion: v1
kind: ConfigMap
metadata:
  name: conveyor-config
  namespace: credit-conveyor
data:
  SPRING_PROFILES_ACTIVE: dev
  SERVER_PORT: "8080"
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/conveyor_db