apiVersion: v1
kind: Secret
metadata:
  name: conveyor-secret
  namespace: credit-conveyor
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: conveyor_user
  SPRING_DATASOURCE_PASSWORD: conveyor_password
  POSTGRES_USER: conveyor_user
  POSTGRES_PASSWORD: conveyor_password
  POSTGRES_DB: conveyor_db